@startuml workflow
left to right direction
object dataset
object label
object evaluate

object model
object preprocessing
object train
object predict

object config

config .down.o dataset
config .o label
config .o evaluate
config .down.o model
config .down.o preprocessing
config .o train
config .o predict

dataset o-right- preprocessing
evaluate o- dataset
evaluate o- model
train o-up- dataset
train o-up- model
predict o- dataset
predict o- model
label o- dataset

@enduml
